version: "3.9"
services:
  web:
    image: domdomi/wizmall
    volumes:
      - ./wizmall/:/var/www/
    ports:
        - 80:80

  db:
    image: mysql/mysql-server:5.7.37
    environment:
      MYSQL_DATABASE: wizmall
      MYSQL_USER: wizmall
      MYSQL_PASSWORD: wizmall
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql